# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='followers',
            new_name='coowners',
        ),
    ]
