# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list', '0002_auto_20160727_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='list_owner',
            new_name='creator',
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
