# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list', '0005_auto_20160727_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
